function resume(){
    let firstname;
    firstname=document.getElementById('firstname').value;
    let middlename;
    middlename=document.getElementById('middlename').value;
    let lastname;
    lastname=document.getElementById('lastname').value;
    console.log(firstname);
    console.log(middlename);
    console.log(lastname);
    document.getElementById('name').innerHTML=firstname +middlename +lastname;
    let email;
    email=document.getElementById('page').value;
    console.log(email);
    document.getElementById('mail').innerHTML=email;
    let contact;
    contact=document.getElementById('pno').value;
    console.log(contact);
    document.getElementById('no').innerHTML=contact;
    let date;
    date=document.getElementById('dob').value;
    console.log(date);
    document.getElementById('date').innerHTML=date;
    let address;
    address=document.getElementById('add').value;
    console.log(address);
    document.getElementById('addr').innerHTML=address;
    let city;
    city=document.getElementById('city').value;
    console.log(city);
    document.getElementById('cit').innerHTML=city;
    let pincode;
    pincode=document.getElementById('pin').value;
    console.log(pincode);
    document.getElementById('pc').innerHTML=pincode;
    let gender;
    gender=document.getElementById('gen').value;
    console.log(gender);
    document.getElementById('ge').innerHTML=gender;
}